import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { ClerkProvider } from "@clerk/nextjs";

const font = Poppins({
  weight:['200','400','500','600','700','800'],
  subsets:['latin']
 })

export const metadata: Metadata = {
  title: "Anshika Infotech",
  description: "Generated by Anshika Infotech",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
        <ClerkProvider>
    <html lang="en">
      <body
        className={`${font.className} antialiased`}
      > 
        {children}
      </body>
    </html>
    </ClerkProvider>
  );
}
